---
- name: Update existing packages
  become: yes
  apt: update_cache=yes

- name: Install required packages
  become: yes
  apt: pkg="{{ item }}" state=latest
  with_items: "{{ server.packages }}"
  when: server.packages is defined

- name: Configure the timezone
  become: yes
  shell: timedatectl set-timezone {{server.timezone}}

- name: Configure the locale
  become: yes
  shell: localectl set-locale {{server.locale}}
