---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Install PHP packages
  become: yes
  apt: pkg="{{ item }}" state=latest
  with_items: "{{ php.packages }}"
  when: php.packages is defined

- include: configure.yml
