---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: Change default nginx site
  sudo: yes
  template: src=../../../../.vhosts/nginx-local.conf dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: Set Nginx config
  sudo: yes
  template: src=nginx.tpl dest=/etc/nginx/nginx.conf
  notify: restart nginx
