---
- name: Install xDebug
  become: yes
  apt: pkg=php-xdebug state=latest

- name: Configure xDebug
  become: yes
  template: src=xdebug.ini.tpl dest=/etc/php/7.0/mods-available/xdebug.ini
  notify: restart php7.0-fpm
